### ISSUE TITLE
Number serialization departs from "de-facto" standard

### ISSUE THREAD

**Issue by cyberphone** [BlockchainCommons/WIPs-IETF-draft-deterministic-cbor#1]
Although there is nothing fundamentally wrong with dCBOR's take on the matter, it departs from an informal "de-facto" standard.  In the table in
https://www.rfc-editor.org/rfc/rfc8949.html#section-appendix.a
you can find that the value ```-4.0``` is supposed to serialize as ```0xf9c400```.  However, in the current version of dCBOR it would serialize as ```0x23```.   This table is (unsurprisingly) also the foundation for the encoding used by the CBOR playground (https://cbor.me/) maintained by the principal CBOR RFC author, Carsten Bormann.

IMO, dCBOR would from an _adoption point of view_ gain by sticking to the de-facto standard.  The downside of the occasionally non-optimal number representation is not a showstopper.  Regarding determinism, the only hard requirement is that you get repeatable results which both solutions provide.

I understand that one of the motives behind the current design, was to relieve _developers_ from CBOR number serialization details.  This is probably not possible using the de-facto standard.  However, a properly designed Gordian Envelope "builder" API should be able shielding _user level_ developers from _all_ serialization issues, like https://www.bouncycastle.org/docs/pkixdocs1.5on/org/bouncycastle/cert/X509v3CertificateBuilder.html.

**Comment by cyberphone** [comment]
Regarding the CBOR RFC, issues with numbers are not limited to floating point.  _The 65-bit integer arrangement is effectively incompatible with all traditional programming platforms_ like C, C++, Java, and C#, where "normal" integers reflect the underlying hardware which today means 64-bit numbers in two-complement notation.  None of these platforms are able to "printf" a CBOR negative number. It must be an extremely rare situation where an application would need exactly 65-bit.  The proper solution would have been to implement `unsigned` (0 to 2^64-1) and `signed` integers (-2^63 to 2^63-1) and anything requiring more would have to go to `Bignum`.  Mixing these types was never a good idea because they are distinct in most platforms and should therefore not mix in protocols either.  It comes to no surprise that COSE does not use `Bignum` for RSA parameters. In platforms having a universal number type such a distinction doesn't make sense but it has no drawback either (it is invisible since it taken care of at the encoder/decoder level).

That 1099511627776.0 results in 5 bytes compared to 9 bytes (!) for 1099511627776 shows in clear that CBOR number encoding got wrong early on and there is nothing we can do about that 😱

That 40-bit integers requires 2 bytes less in Bignum representation compared to integers is another proof of that numbers haven't been properly architected.

However, this is (in similarity to floating point serialization), too late to fix.  The impact on applications is also likely to be negligible.

**Comment by cyberphone** [comment]
I forgot one (potentially) important feature: the ability to represent deterministic CBOR in diagnostic notation.  This requires a _bidirectionally_ compliant serialization scheme like the one used by the CBOR playground. 

Since parsing diagnostic notation is outside of the RFC, I added this to my documentation:
https://cyberphone.github.io/javaapi/org/webpki/cbor/package-summary.html#diagnostic-notation

**Comment by cyberphone** [comment]
Regarding Appendix A, Carsten Bormann writes:
>It is not marked as informative because it is normative.
As far as examples can be normative, of course.
But if your CBOR diagnostic notation implementation does not handle these examples as given, it is not a CBOR diagnostic notation implementation.

That is, Carsten believes that your draft is intended as an _application level_ solution.  I thought it was an encoder/decoder level specification.

**Comment by wolfmcnally** [comment]
I believe this has been discussed to the CBOR WG's general satisfaction.

**Comment by cyberphone** [comment]
The WG is happy because they are not aware of the difference between high-level and low-level.  dCBOR encoding of 2.0 breaks schema based decoders of the kind I work with and in the other direction a CDE-encoded 2.0 breaks a dCBOR decoder.

**Comment by wolfmcnally** [comment]
@cyberphone I think tarring the WG members as not understanding the difference between "high level" and "low level" is pretty condescending.

I'm not sure what sort of schema-based decoders you work with, but I'm not sure why it matters: being compatible with every existing tool is a non-goal for dCBOR. Likewise, as I have said from the start, all CBOR (and CDE) is not valid dCBOR, and that is by design. You don't have to *like* the design or use it, but we have explained our rationale for it ad nauseam and the WG has accepted it.

Anders, you seem to be a voice crying in the wilderness here. May I suggest you take a break and let the WG business move forward? You don't seem to have any new arguments, and I'm tired of giving you the same responses that the rest of the WG is clearly on board with.
